### ISSUE TITLE
Parser returned from timeParse returns a different time zone

### ISSUE THREAD

**Issue by jjnilton** [d3/d3-time-format#101]
The parser returned from `timeParse` method returns a Date object with the year 1900 and a different time zone when compared with creating a Date object. Also, the specifier for the time zone offset doesn't seem to be working:

```
  const date1 = d3.timeParse("%M:%S %Z")("30:45 -0300")
  console.log(date1)
  const date2 = d3.timeParse("%M:%S")("30:45")
  console.log(date2)
  const date3 = new Date(1800000)
  console.log(date3)
```

Result:

```
Date Mon Jan 01 1900 00:24:17 GMT-0306 (Brasilia Standard Time)
runner-4.1.8.min.js:1:9013
Date Mon Jan 01 1900 00:30:45 GMT-0306 (Brasilia Standard Time)
runner-4.1.8.min.js:1:9013
Date Wed Dec 31 1969 21:30:00 GMT-0300 (Brasilia Standard Time)
runner-4.1.8.min.js:1:9013
```

https://jsbin.com/pezisituzi/1/edit?js,console

**Comment by mbostock** [comment]
This is the expected behavior. If you don’t want the year 1900, you need to include the year in the parsed string. For example:

```js
d3.timeParse("%Y %M:%S %Z")("2000 30:45 -0300")
```

https://observablehq.com/d/db690b1cc9d4e712
