### ISSUE TITLE
Doc: %S range

### ISSUE THREAD

**Issue by Benbinbin** [d3/d3-time-format#110]
The [document](https://github.com/d3/d3-time-format#locale_format) says:

> `%S` - second as a decimal number [00,61].

but this [live code example](https://observablehq.com/@bumbeishvili/d3-timeformat-playground) show that the range maybe `[00, 59]`

**Comment by mbostock** [comment]
The range can include 60 or 61 when there are [leap seconds](https://en.wikipedia.org/wiki/Leap_second).

**Comment by mbostock** [comment]
For reference, https://pubs.opengroup.org/onlinepubs/007908799/xsh/strftime.html:

> The range of values for %S is [00,61] rather than [00,59] to allow for the occasional leap second and even more infrequent double leap second.

**Comment by Benbinbin** [comment]
Thanks for reply
