### ISSUE TITLE
%Z behavior does not match strftime

### ISSUE THREAD

**Issue by chasetec** [d3/d3-time-format#111]
The docs say that d3-time-format provides a JavaScript implementation of [strftime](http://pubs.opengroup.org/onlinepubs/007908799/xsh/strftime.html)

However if you read the linked Single UNIX Specification behavior for %Z it should provide "timezone name or abbreviation".

````
const commonTime = d3.timeFormat('%d/%b/%Y:%H:%M:%S %Z');
console.log(commonTime(new Date()));
````

Is producing 19/Feb/2022:11:39:16 -0600 which shows the timezone offset from UTC in the ISO 8601:2000 standard format ( +hhmm or -hhmm ), not a name or abbreviation.

The current behavior of %Z matches what was later added to [updated strftime](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strftime.html) as %z.

To match strftime, swap %Z to %z and add %Z to display timezone as a name or abbreviation.

**Comment by chasetec** [comment]
Name or abbreviation would be something like Central Daylight Time or CDT.

**Comment by mbostock** [comment]
This library isn’t intended to be exactly compatible with strftime in UNIX, or similar methods in Python, e.g. The documentation for %Z in the README looks correct. Also JavaScript won’t have support for named timezones until the Temporal API is widely available (at least not without major workarounds) so this probably would be hard to support anyway.
