### ISSUE TITLE
timezone without 00, e.g +08 , instead of +0800?

### ISSUE THREAD

**Issue by kuchaguangjie** [d3/d3-time-format#114]
When use `%Z` to format date, the timezone has suffix `00`.
Is it possible to remove them from the api, e.g `+08` , instead of `+0800`?

**Comment by Fil** [comment]
The format for timezone (https://github.com/d3/d3-time-format/blob/main/src/locale.js#L594) is not configurable. I would slice the resulting string with `format(date).slice(0, -2)`.
