### ISSUE TITLE
Microseconds (%f)

### ISSUE THREAD

**Issue by ebergmundur** [d3/d3-time-format#24]
Hi

I'm having a problem parsing UTC timestamps with 6 digits.  
`2016-10-06T20:32:56.523411Z`

It works just fine with three digits. 
I'm working with realtime data so it could be messy and heavy workaround to shorten this before parsing. And changes at the source could be hard to get trough.

**Comment by mbostock** [comment]
Those aren’t milliseconds; they are nanoseconds.

**Comment by ebergmundur** [comment]
The %L does not like them any better 
It seems that the parser only works for the ECMA 262 but not  ISO 8601 format.

**Comment by mbostock** [comment]
There is no directive for parsing nanoseconds. There is only %L, which is for milliseconds.

**Comment by ebergmundur** [comment]
That is actually the core of my problem ;-) 
I'll see if I can get changes made to the json feed.

**Comment by ebergmundur** [comment]
I found that a little workaround works, since I'm actually not using the fine details of nanoseconds, and it seem not to screw up the Date() creation. 

Using double %L in the template actually works.

`'%Y-%m-%dT%H:%M:%S.%L%LZ'`

**Comment by mbostock** [comment]
I would strongly not recommend that approach because it means that the last three digits of the nanoseconds field are interpreted as the milliseconds, rather than the first three digits.

```js
var parseTime = d3.utcParse("%Y-%m-%dT%H:%M:%S.%L%LZ");

parseTime("2016-10-06T20:32:56.523411Z").getUTCMilliseconds(); // 411, not 523
```

If you know the format is strictly `%Y-%m-%dT%H:%M:%S.%LXXXZ`, why not just strip the last three nanosecond digits *XXX* before parsing?

```js
var parseMilliseconds = d3.utcParse("%Y-%m-%dT%H:%M:%S.%LZ"),
    stripNanoseconds = function(s) { return s.slice(0, -4) + "Z"; },
    parseTime = function(s) { return parseMilliseconds(stripNanoseconds(s)); };

parseTime("2016-10-06T20:32:56.523411Z"); // Thu, 06 Oct 2016 20:32:56 GMT
```

[Example.](https://runkit.com/57d8702e1ff21014007f12d5/57f6d793353eb60014eacbbb)

**Comment by ebergmundur** [comment]
I realize that, but for now it works for me since I'm only using minutes as the finest grinder and just working on  preliminary stage. 
But as you point out it does not deliver the correct data. 

As a matter of fact I'm testing the c3 library that of course relies on d3 and d3-time-format, but it does not give me any handle on the data itself and I was looking for a solution that could create simple graph with few lines of code. 

Of course I could fetch the json and create suitible dataset but that would take me astray from this mission of simplifying the making of graphs :-)

**Comment by mbostock** [comment]
I see—so you can specify the format but not an arbitrary function for parsing.

A nanosecond directive would be reasonable so I’ll leave this open as a feature request.

**Comment by ebergmundur** [comment]
I actually did that previously, parse the data set, but it took some effort on a full set of data, 3*60*24, or 4.320 entries and made a simple graph too slow.

**Comment by mbostock** [comment]
The cost of a single additional *string*.slice to strip the extra digits does not significantly increase the cost of date parsing (which already calls *string*.slice many times).

**Comment by liugangnhm** [comment]
```js
var d3 = require("d3-time-format")

var parser = d3.timeParse("%Y-%m-%d %H:%M:%S.%f")

var date1 = parser("2017-09-29 19:20:38.888377")
var date2 = parser("2017-09-29 19:20:38.888376")

console.log(date1 > date2, date1 < date2)
```

the result is 
```
false false
```


is there any way to compare the two date obj?

**Comment by mbostock** [comment]
@liugangnhm JavaScript Date objects only have millisecond resolution.

**Comment by liugangnhm** [comment]
@mbostock all right,  I was looking for a javascript module that can parse time string with millisecond and this is the only one i hava found. but it seems that it could only parse .
