### ISSUE TITLE
'%X' is unuseful in timeParse

### ISSUE THREAD

**Issue by ONEBOYS** [d3/d3-time-format#26]
Run this code: 
`d3.timeParse('%Y-%m-%dT%X')('2014-09-25T00:00:00');  `
will be return null;

But I replace '%X' with '%H:%M:%S' , it work

**Comment by mbostock** [comment]
That’s because `%X` is equivalent to `%-I:%M:%S %p` in the default en-US locale, not `%H:%M:%S`.

```js
d3.timeParse('%Y-%m-%dT%X')('2014-09-25T12:00:00 PM') // Thu Sep 25 2014 12:00:00 GMT-0700 (PDT)
```
