### ISSUE TITLE
react version

### ISSUE THREAD

**Issue by imkiven** [d3/d3-time-format#27]
Hello,perhaps d3-time-format does not support react@15.3.2,logs follow:

The package react@15.3.2 does not satisfy its siblings' peerDependencies requirements!

npm ERR! peerinvalid Peer react-d3-tooltip@1.4.14 wants react@^0.14.7
npm ERR! peerinvalid Peer react-d3-zoom@1.1.2 wants react@^0.14.1
npm ERR! peerinvalid Peer react-d3-basic@1.6.11 wants react@^0.14.7
npm ERR! peerinvalid Peer react-d3-brush@1.1.0 wants react@^0.14.0

**Comment by mbostock** [comment]
Did you mean to file this somewhere in https://github.com/react-d3? This repository has nothing to do with React.
