### ISSUE TITLE
ISO weekday number (%u)

### ISSUE THREAD

**Issue by adius** [d3/d3-time-format#31]
ISO weekdays are Monday based and numbered 1-7, but d3 only provides `%w`, which is Sunday based and numbered 0-6.

E.g. [momentjs](https://momentjs.com/docs/#/displaying)  uses `E` for ISO weekday.

**Comment by mbostock** [comment]
Reference: https://en.wikipedia.org/wiki/ISO_week_date

**Comment by mbostock** [comment]
Related #8; having ISO 8601 weekday number is not especially useful without also having support for ISO 8601 week numbers. (%U and %W are *not* ISO 8601 week numbers.)

**Comment by mbostock** [comment]
For consistency with [strftime](http://man7.org/linux/man-pages/man3/strftime.3.html) this should use the `%u` directive.

**Comment by mbostock** [comment]
Fixed in #36.
