### ISSUE TITLE
Missing directives

### ISSUE THREAD

**Issue by GerardoFurtado** [d3/d3-time-format#38]
The standalone library contains these directives for the specifier string:

    var parses = {
        "a": parseShortWeekday,
        "A": parseWeekday,
        "b": parseShortMonth,
        "B": parseMonth,
        "c": parseLocaleDateTime,
        "d": parseDayOfMonth,
        "e": parseDayOfMonth,
        "f": parseMicroseconds,
        "H": parseHour24,
        "I": parseHour24,
        "j": parseDayOfYear,
        "L": parseMilliseconds,
        "m": parseMonthNumber,
        "M": parseMinutes,
        "p": parsePeriod,
        "Q": parseUnixTimestamp,
        "s": parseUnixTimestampSeconds,
        "S": parseSeconds,
        "u": parseWeekdayNumberMonday,
        "U": parseWeekNumberSunday,
        "V": parseWeekNumberISO,
        "w": parseWeekdayNumberSunday,
        "W": parseWeekNumberMonday,
        "x": parseLocaleDate,
        "X": parseLocaleTime,
        "y": parseYear,
        "Y": parseFullYear,
        "Z": parseZone,
        "%": parseLiteralPercent
    };

However, the default bundle (version 4.11.0 at the time of writing) contains only these:

    var parses = {
        "a": parseShortWeekday,
        "A": parseWeekday,
        "b": parseShortMonth,
        "B": parseMonth,
        "c": parseLocaleDateTime,
        "d": parseDayOfMonth,
        "e": parseDayOfMonth,
        "H": parseHour24,
        "I": parseHour24,
        "j": parseDayOfYear,
        "L": parseMilliseconds,
        "m": parseMonthNumber,
        "M": parseMinutes,
        "p": parsePeriod,
        "S": parseSeconds,
        "U": parseWeekNumberSunday,
        "w": parseWeekdayNumber,
        "W": parseWeekNumberMonday,
        "x": parseLocaleDate,
        "X": parseLocaleTime,
        "y": parseYear,
        "Y": parseFullYear,
        "Z": parseZone,
        "%": parseLiteralPercent
    };

As you can see, it is missing: `"f"`, `"Q"`, `"s"`, `"V"` and `"u"`.

Because of that, some users are facing issues when using just the default bundle. Two recent examples can be seen [here](https://stackoverflow.com/q/47043555/5768908) and [here ](https://stackoverflow.com/q/47008978/5768908) (in this last one the user was incorrectly using `"%L"`, but changing for `"%f"` - which is the correct specifier - will return `null`).

I don't know if this was intentional, but I don't think so.

Cheers,

**Comment by mbostock** [comment]
The D3 default bundle does not yet include the latest release of this library but will be updated in the near future.

**Comment by GerardoFurtado** [comment]
Thanks for your reply, good to know that. Cheers,

**Comment by GerardoFurtado** [comment]
Thanks for your promptly reply. Only _after_ opening this issue I realised that the standalone microlibrary's last version was released on 9th October, while the default bundle's last version was released on 3rd October, and that explains why it doesn't contain the latest directives. I'll be more careful before opening an issue next time.

Cheers,
