### ISSUE TITLE
IsoWeekYear ?

### ISSUE THREAD

**Issue by Niekes** [d3/d3-time-format#42]
Additionaly to %u and %V:

````javascript
d3.timeFormat('%t')(new Date(2016, 0, 1)); // 2015
````

**Comment by BrianMitchL** [comment]
Which strftime/strptime operator is this? All `%t` seems to refer to is a tab character (`\t`). Could this be `%G` as seen in the [C++ strftime](https://en.cppreference.com/w/cpp/chrono/c/strftime)?

**Comment by Niekes** [comment]
@BrianMitchL Do you know when you can solve this issue?

Thanks for your work and effort!

**Comment by mbostock** [comment]
Fixed in #52?
