### ISSUE TITLE
typo in zh-CN.json 周 should be 週

### ISSUE THREAD

**Issue by muyueh** [d3/d3-time-format#50]
https://github.com/d3/d3-time-format/blob/master/locale/zh-CN.json#L7

it's currently: 
`"shortDays": ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],`
but this is a typo, it should be: 
`"shortDays": ["週日", "週一", "週二", "週三", "週四", "週五", "週六"],`

reference: https://zh.wikipedia.org/wiki/%E6%98%9F%E6%9C%9F%E4%B8%80

**Comment by muyueh** [comment]
This might be a separate issue, but as this is the `shortDays`, I will further suggest to remove the  週 from 週ㄧ: 

"shortDays": ["日", "一", "二", "三", "四", "五", "六"],

**Comment by cdmikechen** [comment]
zh-CN 代表的是中国大陆汉字 都是简体。如果想要繁体可以根据locale区域代码自己配置

**Comment by Fil** [comment]
> zh-CN stands for Chinese characters in mainland China are simplified. If you want Traditional Chinese, you can configure it according to the locale code

Yes, thank you. The locale for traditional chinese is [zh-TW](https://github.com/d3/d3-time-format/blob/master/locale/zh-CN.json), so for the OP should just switch to locale zh-TW.

On the second issue, however, CLDR seems to recommends two glyphs for *short* days in  [simplified](https://github.com/PrestaShop/PrestaShop/blob/develop/localization/CLDR/core/common/main/zh.xml#L2723) and 1 glyph for [traditional](https://github.com/PrestaShop/PrestaShop/blob/develop/localization/CLDR/core/common/main/zh_Hant.xml#L4519) (as well as for the "narrow" format, which d3 doesn't have).

So if I read this correctly, we would have to update [zh-TW](https://github.com/d3/d3-time-format/blob/master/locale/zh-CN.json) to make `"shortDays": ["日", "一", "二", "三", "四", "五", "六"],`.

**Comment by muyueh** [comment]
> Yes, thank you. The locale for traditional chinese is [zh-TW](https://github.com/d3/d3-time-format/blob/master/locale/zh-CN.json), so for the OP should just switch to locale zh-TW.

Thank you. I was not aware of the existence of zh-TW. 

I just learned that in "周" was the correct word to be used in zh-CN. I thought this was a typo, my bad. 

> On the second issue, however, CLDR seems to recommends two glyphs for _short_ days in [simplified](https://github.com/PrestaShop/PrestaShop/blob/develop/localization/CLDR/core/common/main/zh.xml#L2723) and 1 glyph for [traditional](https://github.com/PrestaShop/PrestaShop/blob/develop/localization/CLDR/core/common/main/zh_Hant.xml#L4519) (as well as for the "narrow" format, which d3 doesn't have).
> 
> So if I read this correctly, we would have to update [zh-TW](https://github.com/d3/d3-time-format/blob/master/locale/zh-CN.json) to make `"shortDays": ["日", "一", "二", "三", "四", "五", "六"],`.

Yes. I just made a pull request accordingly. 
https://github.com/d3/d3-time-format/pull/84

Thank you @cdmikechen @Fil for clarifying. I am closing this issue.
