### ISSUE TITLE
Add support for quarter?

### ISSUE THREAD

**Issue by kanitw** [d3/d3-time-format#56]
Like:

Jan, Feb, Mar = 1
Apr, May, June = 2

and so on.   

Given `%Q` is taken, perhaps `%q`?

**Comment by mbostock** [comment]
I’m probably not doing to add any new features to this library; see #57.

**Comment by jheer** [comment]
I understand the rationale of #57 regarding the long-term future of this package. Nevertheless, Vega will depend on d3-time-format for some time to come (at minimum until version 6, given likely breaking changes when moving to a different formatting system). Moreover, including quarters is valuable in a number of visualization contexts (especially business / finance applications).

So, on the off chance that @mbostock is open to it, I've filed a PR (#58) for adding a `%q` directive for quarter of the year. Thanks for considering it!

**Comment by mbostock** [comment]
Merged #58 and added parsing support for %q, too.
