### ISSUE TITLE
Deprecate in favor of date.toLocaleString?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-time-format#57]
I’m currently considering the long-term plan for this library.

JavaScript’s native support for localized date and time formatting has improved dramatically since D3 was first created (and [pv.Format.time](https://github.com/mbostock/protovis/blob/master/src/text/TimeFormat.js) in Protovis before that). In particular, the fact that *date*.toLocaleString automatically uses the browser’s current locale is such a huge improvement (less en-US-centric) that I feel promoting d3-time-format’s continued use is harmful.

https://observablehq.com/@mbostock/date-formatting

There is also a nice standard for relative time format, Intl.RelativeTimeFormat:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat

It hasn’t made it to Edge and Safari yet, but Edge will eventually be Chromium, and Safari will hopefully come around. I expect therefore it would be better to encourage adoption of the standard and perhaps offer a polyfill than to compete with the proposed standard.

**Comment by mbostock** [comment]
I have noticed that *date*.toLocaleString is extremely slow, but perhaps browser vendors haven’t realized that and will make performance improvements as it is adopted by web developers.

**Comment by mbostock** [comment]
Since there is no standard for parsing dates (yet), it probably makes sense to retain part of this library as an optional D3 module that only implements parsing (not formatting).

But we also probably want a strict ECMAScript IEEE 8601 date parser, and possibly shorthand formatter as well, since browser support for that is not quite where it should be and there is still an active TC39 proposal to standardize the behavior of Date.parse.

**Comment by mbostock** [comment]
Here are the relevant bits from d3-dsv to parse and format ECMAScript dates strictly:

https://github.com/d3/d3-dsv/blob/master/src/autoType.js
https://github.com/d3/d3-dsv/blob/master/src/dsv.js

**Comment by curran** [comment]
FWIW, `date.toLocaleString` seems to have [pretty good coverage](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString#Browser_compatibility) - everything except Android webview.

![image](https://user-images.githubusercontent.com/68416/61280847-3ecd6980-a7d6-11e9-8a9b-7c7d980edc34.png)

**Comment by mbostock** [comment]
Unfortunately *date*.toLocaleString is far too slow for many applications (e.g., when formatting thousands of dates for static tooltips). But I haven’t yet tested whether creating an Intl.DateTimeFormat instance would be faster. If it is, that may be a viable replacement for this library.

**Comment by curran** [comment]
A benchmark would be good to have on hand, so we could easily check if browser vendors make performance improvements. Is there an example you know of that demonstrates or measures the slowness?

**Comment by mbostock** [comment]
I think this library still serves a purpose, at least as far as parsing goes, and it’s nice to have symmetry with formatting. Therefore closing this issue.
