### ISSUE TITLE
Time format/parse treat week numbers inconsistently

### ISSUE THREAD

**Issue by jheer** [d3/d3-time-format#62]
Using Sunday-based week and day-of-week numbers, the format and parse methods treat week zero inconsistently. This can cause round-tripping of a date to fail. Based on the documentation, my understanding is that week one commences with the first Sunday of the year, and days prior to that lie in week zero. If so, it looks like the format method is buggy.

```js
d3.timeFormat('%Y %U %w')(new Date(2012, 0, 1)) // "2012 00 0" -> should be "2012 01 0"?
d3.timeParse('%Y %U %w')('2012 00 0').toLocaleString() // "12/25/2011, 12:00:00 AM"
d3.timeParse('%Y %U %w')('2012 01 0').toLocaleString() // "1/1/2012, 12:00:00 AM"

d3.utcFormat('%Y %U %w')(new Date(Date.UTC(2012, 0, 1))) // "2012 00 0"
d3.utcParse('%Y %U %w')('2012 00 0').toUTCString() // "Sun, 25 Dec 2011 00:00:00 GMT"
```

Using Monday-based week and day-of-week numbers exhibits the same problem:

```js
d3.timeFormat('%Y %W %u')(new Date(2018, 0, 1)) // "2018 00 1" -> should be "2018 01 1"?
d3.timeParse('%Y %W %u')('2018 00 1').toLocaleString() // "12/25/2017, 12:00:00 AM"
d3.timeParse('%Y %W %u')('2018 01 1').toLocaleString() // "1/1/2018, 12:00:00 AM"

d3.utcFormat('%Y %W %u')(new Date(Date.UTC(2018, 0, 1))) // "2018 00 1"
d3.utcParse('%Y %W %u')('2018 00 1').toUTCString() // "Mon, 25 Dec 2017 00:00:00 GMT"
```

**Comment by jheer** [comment]
I believe the error stems from the use of `timeSunday` and `timeMonday`:

- [locale.js#L527](https://github.com/d3/d3-time-format/blob/master/src/locale.js#L527)
- [locale.js#L541](https://github.com/d3/d3-time-format/blob/master/src/locale.js#L541)

For example:

```js
function formatWeekNumberSunday(d, p) {
  return pad(timeSunday.count(timeYear(d), d), p, 2);
}
```

In most cases the flooring performed inside `timeSunday.count` shifts the starting date value to the prior Sunday (the week zero boundary). However, if the first day of the year is itself a Sunday, the starting date value gets floored to the week one boundary instead, resulting in an off-by-one-week error. One solution might be to add logic that suitably prepares the first argument to `count` so that it maps to the week zero boundary.

(Similar reasoning then applies for Monday-based weeks.)

**Comment by mbostock** [comment]
This certainly looks like a bug! Thanks for the report.

**Comment by mbostock** [comment]
Test cases as a notebook: https://observablehq.com/d/d1cc30312fd3d256

I agree that d3.timeFormat looks wrong here; 2012-01-01, a Sunday, should be considered week 1. d3.timeParse appears to be parsing the week number correctly.

Strangely, though, I think d3.utcParse is showing a separate error. I would expect `d3.utcParse("%Y %U %w")("2012 01 0")` to return Sunday 2012-01-01, but it returns Monday 2012-01-02.
