### ISSUE TITLE
Unavailable locales on CDN unpkg.com since version 2.2

### ISSUE THREAD

**Issue by villers** [d3/d3-time-format#66]
GET https://unpkg.com/d3-time-format@2.2.0/locale/en-US.json 404
GET https://unpkg.com/d3-time-format@2.2.0/locale/fr-FR.json 404

https://unpkg.com/d3-time-format@2/locale/en-US.json redirect to GET https://unpkg.com/d3-time-format@2.2.0/locale/en-US.json 404

GET https://unpkg.com/d3-time-format@2.1.0/locale/en-US.json 200

**Comment by kmondedd** [comment]
Same issue... 

Thanks for `GET https://unpkg.com/d3-time-format@2.1.0/locale/en-US.json 200`

**Comment by lapidus** [comment]
Same here ...

**Comment by lapidus** [comment]
Hint: Short term workaround. Fixing it to for example "2.1.2" produces the locale/ folder ...

**Comment by mbostock** [comment]
Apologies. Fix in coming.
