### ISSUE TITLE
t.timeFormat is not a function

### ISSUE THREAD

**Issue by rsangin** [d3/d3-time-format#67]
Hi, 
The last version of this package (2.2.1) is having errors in angular production build. Before this package d3-color had the same exact problem in prod build. 
I don't know what's happening but it's making our app unstable. This is the second time in less than a month that it's happening in d3 package.
The error now that we are facing is this: 

**t.timeFormat is not a function**

**Comment by gordonwoodhull** [comment]
It’s probably the fault of the angular optimizer - see https://github.com/d3/d3-color/issues/68#issuecomment-537147753

**Comment by mbostock** [comment]
Yep, see angular/angular-cli#11439.
