### ISSUE TITLE
%Y matches two digit year on parse

### ISSUE THREAD

**Issue by daveroberts** [d3/d3-time-format#78]
utcParse("%Y/%m/%d")
matches the string "10/12/68", assuming the year is 10AD.

I would expect this to not match, and only match if the year is four digits long

**Comment by mbostock** [comment]
It matches up to four digits, but not four digits exactly. Changing this behavior would not be backwards-compatible, so we can’t easily change it. I would welcome a PR to the README that documents the behavior, or a proposal for how to make this strict while preserving backwards compatibility, if that’s what you want.

**Comment by daveroberts** [comment]
Thanks for the reply.  Can you explain roughly what you mean by maintaining backwards compatibility?  By definition, any change to the behavior of the parser would break backwards compatibility.  What changes are okay, and what changes are off limits?

**Comment by mbostock** [comment]
Changing the behavior of an existing specifier. Introducing a new specifier would probably be okay.
