### ISSUE TITLE
Bower doesn't include the compiled js file, only the source.

### ISSUE THREAD

**Issue by ambischof** [d3/d3-time-format#9]
The npm install correctly retrieves the build directory, but the bower only retrieves the source files as seen in the repository.

**Comment by mbostock** [comment]
Is there a way to include compiled files in a Bower package yet? Or point to the release zip? Because I don’t want to check the compiled files into the source repository.

**Comment by mbostock** [comment]
Related bower/bower#1606.

**Comment by mbostock** [comment]
It looks like this would work, if we add the bower.json or package.json to the release assets (which is trivial for me to do):

`bower install https://github.com/d3/d3-time-format/releases/download/v0.1.4/time-format.zip`

**Comment by ambischof** [comment]
If that works, it would save a lot of workaround on the client end! Thanks!

**Comment by mbostock** [comment]
Yeah, but it’s still not ideal because `bower install d3-time-format` won’t do the right thing.

**Comment by mbostock** [comment]
Punting on Bower support for now. I might jump through all the tedious hoops in the future, or perhaps Bower will add support for publishing generated files.
