### ISSUE TITLE
Locale files not exported

### ISSUE THREAD

**Issue by herrstucki** [d3/d3-time-format#98]
Since switching to `type: module` I can't import the locale JSON files anymore because they're not listed in the exports.

```js
import localeCh from "d3-time-format/locale/de-CH.json";

// => Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './locale/de-CH.json' is not defined by "exports" in ...
```

Is this intentional? The same applies to d3-format.

**Comment by mbostock** [comment]
Not intentional. We should export.
